-- GoalMate schema.
--
-- Conventions
--   * ids are short random TEXT ids generated by the server (lib/ids.js)
--   * *_at columns are TIMESTAMPTZ (moments in time, stored in UTC)
--   * *_date columns are DATE (calendar days in the user's local time zone)
--   * deleted_at marks "in the Trash" (soft delete); rows are removed for good after 30 days
--   * CHECK constraints keep invalid values out even if the application has a bug

CREATE TABLE users (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  is_demo       BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- One account per email, ignoring upper/lower case.
CREATE UNIQUE INDEX users_email_unique ON users (lower(email));

CREATE TABLE goals (
  id           TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title        TEXT NOT NULL,
  description  TEXT NOT NULL DEFAULT '',
  priority     TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low', 'none')),
  status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'archived')),
  color        TEXT NOT NULL DEFAULT 'blue',
  tags         TEXT[] NOT NULL DEFAULT '{}',
  start_date   DATE,
  target_date  DATE,
  ai_generated BOOLEAN NOT NULL DEFAULT false,
  position     DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  deleted_at   TIMESTAMPTZ
);
CREATE INDEX goals_user_idx ON goals (user_id, deleted_at);

CREATE TABLE tasks (
  id               TEXT PRIMARY KEY,
  user_id          TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  goal_id          TEXT REFERENCES goals (id) ON DELETE CASCADE,   -- NULL = Inbox
  parent_id        TEXT REFERENCES tasks (id) ON DELETE CASCADE,   -- set for steps (subtasks)
  title            TEXT NOT NULL,
  description      TEXT NOT NULL DEFAULT '',
  due_date         DATE,
  priority         TEXT NOT NULL DEFAULT 'none' CHECK (priority IN ('high', 'medium', 'low', 'none')),
  difficulty       TEXT CHECK (difficulty IN ('easy', 'medium', 'hard')),
  estimate_minutes INTEGER CHECK (estimate_minutes BETWEEN 1 AND 1440),
  position         DOUBLE PRECISION NOT NULL DEFAULT 0,
  completed_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ
);
CREATE INDEX tasks_user_due_idx ON tasks (user_id, due_date) WHERE deleted_at IS NULL;
CREATE INDEX tasks_goal_idx ON tasks (goal_id);
CREATE INDEX tasks_parent_idx ON tasks (parent_id);
CREATE INDEX tasks_completed_idx ON tasks (user_id, completed_at);

-- Journal entries, notes pages (including a task's notes) and saved weekly reviews.
CREATE TABLE pages (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind       TEXT NOT NULL DEFAULT 'journal' CHECK (kind IN ('journal', 'note', 'review')),
  title      TEXT NOT NULL DEFAULT '',
  icon       TEXT,
  content    JSONB NOT NULL DEFAULT '[]',         -- the editor document (BlockNote blocks)
  plain_text TEXT NOT NULL DEFAULT '',            -- extracted from content: search, excerpts, AI context
  word_count INTEGER NOT NULL DEFAULT 0,
  entry_date DATE,
  mood       SMALLINT CHECK (mood BETWEEN 1 AND 5),
  tags       TEXT[] NOT NULL DEFAULT '{}',
  goal_id    TEXT REFERENCES goals (id) ON DELETE SET NULL,
  task_id    TEXT REFERENCES tasks (id) ON DELETE SET NULL,
  pinned     BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);
CREATE INDEX pages_user_idx ON pages (user_id, deleted_at, entry_date);
-- A task has at most one (non-deleted) notes page.
CREATE UNIQUE INDEX pages_one_per_task ON pages (task_id) WHERE task_id IS NOT NULL AND deleted_at IS NULL;

-- AI coach conversations. thread = 'task:<id>', 'page:<id>' or 'goal:<id>'.
CREATE TABLE messages (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  thread     TEXT NOT NULL,
  role       TEXT NOT NULL CHECK (role IN ('user', 'model')),
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX messages_thread_idx ON messages (user_id, thread, created_at);

-- "Recent activity" feed.
CREATE TABLE activity (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  type       TEXT NOT NULL,          -- goal.created, goal.completed, task.completed, page.created
  entity     TEXT NOT NULL,
  entity_id  TEXT,
  label      TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX activity_user_idx ON activity (user_id, created_at DESC);
